In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
## going to test the new setup
from nba import NBAbase, NBAetl, NBAmodels, NBAdata
#from dev import NBAdata
from betting import odds
import pandas as pd
import seaborn as sns
import sqlite3
import shutil
import numpy as np
from betting import funcs
odds = funcs.odds()
import matplotlib.pyplot as plt

In [10]:
q = '''CREATE TABLE IF NOT EXISTS predictions (
    player_id       TEXT,
    date            TEXT,
    over_under      TEXT,
    number          REAL,
    model_prob      REAL,
    FanDuels         REAL,
    DraftKings      REAL,
    theScore_Bet         REAL,
    ev_fanduel      REAL,
    ev_draftkings   REAL,
    ev_espnbet      REAL,
    bet_book        TEXT,
    final_line      REAL,
    bet_amount      REAL,
    result          REAL,
    PRIMARY KEY (player_id, date, over_under, number)
);'''

In [3]:
etl = NBAetl.etl()
data = NBAdata.data()
odds = funcs.odds()

In [15]:
#run file
#get yesterday's data and load
yst = (dt.datetime.today() + pd.to_timedelta(-1,unit='day')).strftime(format='%Y-%m-%d')
gids = etl.get_games(yst,yst)
print('Updating for {}'.format(yst))
etl.update_player_log([yst])
time.sleep(np.random.randint(5,15))
try:
    etl.update_shots_allowed([yst])
except:
    print('shots not updated yet')
time.sleep(np.random.randint(5,15)) 
etl.update_teamLog(gids.GAME_ID.unique())

#get the model and run the data through the pipeline
threes = NBAmodels.models('threes')

td = data.threes_pipe(threes.data)

td = data.clean_na(td)
td = td[td.game_date==(dt.datetime.today()).strftime('%Y-%m-%d')]
td = threes.standRobust_scaler(td)
#get predictions
preds= threes.model.predict(sm.add_constant(td.filter(threes.features),has_constant='add'))

#name alterations
idInfo = threes.data[threes.data.game_date==dt.datetime.today().strftime('%Y-%m-%d')][['name','team','game_id']]
idInfo.name = data.standardize_names(idInfo.name)

#odds pull
overs = odds.oddsTable(preds,idInfo)


#%2cespnbet
def fetch_odds(market):
    url = odds.market_vars.get(market).get('url')
    df = pd.DataFrame()
    events,akey = odds.oddsData(odds.nbaEvents,usePaid=True)
    for event in events:
        r = requests.get(url.format(event,akey))
        game = r.json()
        for key in game.get('bookmakers'):
            bk = key.get('title')
            for mrkt in key.get('markets'):
                temp = pd.DataFrame(mrkt.get('outcomes'))
                temp.columns = ['over_under','name','price',odds.market_vars.get(market).get('col_name')]
                temp['book'] = bk
                df = pd.concat([temp,df])   
    odf = df.pivot_table(index=['name',odds.market_vars.get(market).get('col_name'),'over_under'],columns=['book']).reset_index()
    odf.columns = [col[1] if col[1]!= '' else col[0] for col in odf.columns]
    return odf
#odds name updates
odf.name = data.standardize_names(odf.name)

#create the data table view
def bet_table(overs,odf,val_col):
    
    final = odf.merge(overs,how='left',on=['name',val_col,'over_under'])
    final['prob'] = np.where(final.value<0, round(abs(final.value) / (abs(final.value) + 100),4), round(100/(final.value +100),4))
    final['DKEV'] = ['{:.2%}'.format(odds.ev(p, odd)) for p,odd in zip(final.prob,final.DraftKings.replace(0,1))]
    final['FanDuelEV'] = ['{:.2%}'.format(odds.ev(p, odd))  for p,odd in zip(final.prob,final.FanDuel.replace(0,1))]
    #final['BetMGMEV'] = ['{:.2%}'.format(odds.ev(p, odd))  for p,odd in zip(final.prob,final.BetMGM)]
    final['espnEV'] = ['{:.2%}'.format(odds.ev(p, odd))  for p,odd in zip(final.prob,final['theScore Bet'])]
    #first row needs to be the tiebreaker row
    final['FanDuelAmount'] = [round(x * odds.budget * odds.kellyVal,2) for x in final.FanDuelKelly.values]
    final['DraftKingsAmount'] = [round(x * odds.budget * odds.kellyVal,2) for x in final.DKKelly.values]
    #final['BetMGMAmount'] = [round(x * odds.budget * odds.kellyVal,2) for x in final.BetMGMKelly.values]
    final['theScore BetAmount'] = [round(x * odds.budget * odds.kellyVal,2) for x in final.espnKelly]
    return final

NameError: name 'dt' is not defined

In [52]:
# run_daily.py

import datetime as dt
import time
import statsmodels.api as sm

def data_pull(run_date=None):
    run_date = run_date or (dt.datetime.today() + pd.to_timedelta(-1, unit='day')).strftime(format='%Y-%m-%d'))
    '''
    Our Daily run to pull in all game data for date requested.  Typically the prior day but can be adjusted for missing data.
    this is for a single day update, run individual functions for bulk loading
    inputs: Optional date, defaults to yesterday
    Outputs: None; provides print statements with updates, logging on errors with tracking data and will refresh opponent data table.
    '''
    gids = etl.get_games(run_date,run_date)
    print('Updating for {}'.format(run_date))
    etl.update_player_log([run_date])
    time.sleep(np.random.randint(5,15))
    etl.update_shots_allowed([run_date])
    time.sleep(np.random.randint(5,15)) 
    etl.update_teamLog(gids.GAME_ID.unique())
    data.refresh_opp_data()

def run_model(model_name,date=None):
    '''
    Run function for the model, this will get the model and produce the predictions both in a long and wide format
    inputs: model name, date that defaults to today
    ouput: long and wide dataframes of predicitons for the day
    '''
    date =  date or (dt.datetime.today() + pd.to_timedelta(-1, unit='day')).strftime(format='%Y-%m-%d')
    model = NBAmodels.models(model_name)
    pipe = model.get(pipe)
    td = pipe(model.data)
    td = data.clean_na(td)
    td = td[td.game_date == date]
    td = model.standRobust_scaler(td)
    preds = model.model.predict(sm.add_constant(td.filter(model.features), has_constant='add'))
    idInfo = model.data[model.data.game_date == date][['name','team','game_id']]
    idInfo.name = data.standardize_names(idInfo.name)
    return odds.oddsTable(preds, idInfo,odds.market_vars.get(model_name).get('col_name')),idInfo,model

data_pull()
overs, idInfo = run_model('threes')
odf = odds.fetch_odds('threes')
final = odds.bet_table(overs,odf,'threesMade')


# def write_predictions(final, conn):
#     today = dt.datetime.today().strftime('%Y-%m-%d')
#     final['date'] = today
#     final['bet_book'] = None
#     final['final_line'] = None
#     final['bet_amount'] = None
#     final['result'] = None
#     final.rename(columns={'threesMade':'number','name':'player_id'}, inplace=True)
#     final[['player_id','date','over_under','number','prob',
#            'DraftKings','FanDuel','ESPN Bet',
#            'ev_draftkings','ev_fanduel','ev_espnbet',
#            'bet_book','final_line','bet_amount','result']].to_sql('predictions', conn, if_exists='append', index=False)



# if __name__ == '__main__':
#     yst = (dt.datetime.today() + pd.to_timedelta(-1, unit='day')).strftime('%Y-%m-%d')
#     conn = sqlite3.connect('nba.db')
#     run_data_update(yst)
#     overs = run_model()
#     odf, o = fetch_odds()
#     final = build_final(overs, odf, o)
#     write_predictions(final, conn)

[autoreload of betting.funcs failed: Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 276, in check
    superreload(m, reload, self.old_objects)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/extensions/autoreload.py", line 475, in superreload
    module = reload(module)
             ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 621, in _exec
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ericcoxon/code/bets/betting/funcs.py", line 8, in <module>
    from constants import books
ModuleNotFoundError: No module named 'constants'
]

Free is out
{'Date': 'Sat, 11 Apr 2026 12:58:11 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '3', 'Connection': 'keep-alive', 'X-Requests-Used': '141', 'X-Requests-Remaining': '19859', 'X-Requests-Last': '0', 'vary': 'Accept-Encoding', 'Apigw-Requestid': 'bp_Hqi58IAMEZiw='}

KeyError: 'name'

In [62]:
odds.market_vars.get('threes').get('col_name')

'threesMade'

In [31]:
end_date = (dt.datetime.today() + pd.to_timedelta(-2,unit='day')).strftime(format='%Y-%m-%d')
start_date = (dt.datetime.today() + pd.to_timedelta(-12,unit='day')).strftime(format='%Y-%m-%d')
df = pd.read_sql('''SELECT game_id,team_id,game_date,wide_fg2a,wide_fg3m,open_fg3m,open_fg3a
                      FROM shotsAllowed WHERE game_date BETWEEN '{}' AND '{}' '''.format(start_date,end_date),etl.conn)

In [121]:
idInfo = run.run_model(model_name,date)

In [122]:
idInfo['name'] = idInfo['name'].str.replace('.','')

In [92]:
date = '2026-03-26'
model_name='threes'
pipes = {'threes':data.threes_pipe}

In [393]:
pd.read_sql('select * from predictions',etl.conn)

     player_id        date  market over_under  number  model_line
0      1626166  2026-03-23  threes       Over     0.5      -461.0
1      1626167  2026-03-23  threes       Over     0.5      -306.0
2      1626171  2026-03-23  threes       Over     0.5      -355.0
3      1626181  2026-03-23  threes       Over     0.5     -2657.0
4      1627739  2026-03-23  threes       Over     0.5      -123.0
...        ...         ...     ...        ...     ...         ...
3700    203991  2026-03-23  threes      Under     9.5     -9900.0
3701    203992  2026-03-23  threes      Under     9.5     -9900.0
3702    204001  2026-03-23  threes      Under     9.5     -9900.0
3703    204456  2026-03-23  threes      Under     9.5     -9900.0
3704      2544  2026-03-23  threes      Under     9.5     -9900.0

[3705 rows x 6 columns]

In [87]:
t, idinfo = chkz

In [276]:
overs,idInfo = run.run_model('threes',date)

In [277]:
#finding odds
odf = pd.read_csv('../nba/data/csv/{}odds.csv'.format(date))
odf.rename(columns = {'threesMade':'number'},inplace=True)
#overs.rename(columns = {'threesMade':'number',inplace=True)

In [278]:
final = odds.bet_table(overs,odf)

In [294]:
import re
amts = [col for col in final.columns if re.search('Amount$',col)!=None]

In [143]:
EVcols = [col for col in final.columns if col.find('Amount')>-1]

In [307]:
final[(final[amts]>1).any(axis=1)]

,name,team,player_id,over_under,number,value,DraftKings,FanDuel,Fanatics,theScore Bet,prob,DraftKingsEV,DraftKingsAmount,FanDuelEV,FanDuelAmount,espnEV,espnAmount
2,Malik Monk,SAC,1628370,Over,0.5,-983,-970.0,-1300.0,NaN,NaN,0.9077,0.13%,1.55,-2.25%,-36.53,nan%,NaN
7,Jalen Brunson,NYK,1628973,Over,0.5,-1026,-990.0,-1300.0,NaN,NaN,0.9112,0.32%,4.01,-1.87%,-30.40,nan%,NaN
16,Coby White,CHA,1629632,Over,0.5,-935,-730.0,-735.0,NaN,NaN,0.9034,2.72%,24.78,2.63%,24.17,nan%,NaN
17,Grant Williams,CHA,1629684,Over,0.5,-389,-248.0,NaN,NaN,NaN,0.7955,11.63%,36.04,nan%,NaN,nan%,NaN
18,Javonte Green,DET,1629750,Over,0.5,-281,-272.0,NaN,NaN,NaN,0.7375,0.86%,2.94,nan%,NaN,nan%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Brandon Miller,CHA,1641706,Under,3.5,-232,-132.0,-142.0,NaN,-140.0,0.6988,22.82%,37.65,19.09%,33.89,19.79%,34.64
703,Daniss Jenkins,DET,1642450,Under,3.5,-1806,NaN,-1450.0,NaN,NaN,0.9475,nan%,NaN,1.28%,23.28,nan%,NaN
737,Saddiq Bey,NOP,1630180,Under,4.5,-1471,NaN,-1400.0,NaN,NaN,0.9363,nan%,NaN,0.32%,5.56,nan%,NaN
750,Brandon Miller,CHA,1641706,Under,4.5,-595,NaN,-340.0,NaN,-285.0,0.8561,nan%,NaN,10.79%,45.85,15.65%,55.75
805,Brandon Miller,CHA,1641706,Under,5.5,-1363,NaN,-900.0,NaN,NaN,0.9316,nan%,NaN,3.51%,39.50,nan%,NaN

In [175]:
','.join(pd.read_sql("select sql from sqlite_master where name = 'predictions' ",etl.conn).sql.values.tolist()).split('\n')

['CREATE TABLE predictions (',
 '    player_id       TEXT,',
 '    date            TEXT,',
 '    over_under      TEXT,',
 '    number          REAL,',
 '    model_prob      REAL,',
 '    FanDuels         REAL,',
 '    DraftKings      REAL,',
 '    theScore_Bet         REAL,',
 '    ev_fanduel      REAL,',
 '    ev_draftkings   REAL,',
 '    ev_espnbet      REAL,',
 '    bet_book        TEXT,',
 '    final_line      REAL,',
 '    bet_amount      REAL,',
 '    result          REAL, user TEXT,',
 '    PRIMARY KEY (player_id, date, over_under, number)',
 ')']

In [177]:
qbets = '''
CREATE TABLE bets (
     player_id       TEXT,
     date            TEXT,
     market          TEXT,
     over_under      TEXT,
     number          REAL,
     bet_book        TEXT,
     final_line      REAL,
     bet_amount      REAL,
     user TEXT,
     PRIMARY KEY (player_id, date, over_under, number)
     )
'''
qpreds = '''
CREATE TABLE predictions (
     player_id       TEXT,
     date            TEXT,
     market          TEXT,
     over_under      TEXT,
     number          REAL,
     model_prob      REAL,
     tracking_complete INTEGER,
     PRIMARY KEY (player_id, date, over_under, number)
     )
'''
qlines = '''
CREATE TABLE lines (
     player_id       TEXT,
     date            TEXT,
     market          TEXT,
     over_under      TEXT,
     number          REAL,
     FanDuel         REAL,
     DraftKings      REAL,
     theScore_Bet    REAL,
     PRIMARY KEY (player_id, date, over_under, number)
     )
'''

In [310]:
etl.cur.execute('ALTER TABLE predictions DROP COLUMN tracking_complete')
etl.conn.commit()

In [186]:
import glob
odds_files = glob.glob('../nba/data/csv/*odds.csv')

In [388]:
pd.read_sql('select * from predictions',etl.conn)

     player_id        date  market over_under  number  model_prob
0      1626166  2026-03-23  threes       Over     0.5      -461.0
1      1626167  2026-03-23  threes       Over     0.5      -306.0
2      1626171  2026-03-23  threes       Over     0.5      -355.0
3      1626181  2026-03-23  threes       Over     0.5     -2657.0
4      1627739  2026-03-23  threes       Over     0.5      -123.0
...        ...         ...     ...        ...     ...         ...
3700    203991  2026-03-23  threes      Under     9.5     -9900.0
3701    203992  2026-03-23  threes      Under     9.5     -9900.0
3702    204001  2026-03-23  threes      Under     9.5     -9900.0
3703    204456  2026-03-23  threes      Under     9.5     -9900.0
3704      2544  2026-03-23  threes      Under     9.5     -9900.0

[3705 rows x 6 columns]

In [231]:
l = []
for f in odds_files:
    d = f[16:f.find('odds')]
    temp = pd.read_csv(f)
    temp['date'] = d
    temp.rename(columns = {'ESPN BET':'theScoreBet','theScore Bet':'theScoreBet'}
                ,inplace=True)

In [232]:
linesdf = pd.concat(l)

In [339]:
pd.read_sql('select * from predictions',etl.conn)

Empty DataFrame
Columns: [player_id, date, market, over_under, number, model_prob]
Index: []

In [9]:

from nba.run import run_model
df, idInfo = run_model('threes',date='2026-03-23')

In [10]:
#add in to your pulls/updates that we check weekly for new players using etl.update_player_info()

In [11]:
df

                    name team player_id over_under number  model_line
195        Cameron Payne  PHI   1626166       Over    0.5        -461
196         Myles Turner  MIL   1626167       Over    0.5        -306
197         Bobby Portis  MIL   1626171       Over    0.5        -355
198        Norman Powell  MIA   1626181       Over    0.5       -2657
199            Kris Dunn  LAC   1627739       Over    0.5        -123
...                  ...  ...       ...        ...    ...         ...
1945        Clint Capela  HOU    203991      Under    9.5       -9900
1946   Bogdan Bogdanovic  LAC    203992      Under    9.5       -9900
1947  Kristaps Porzingis  GSW    204001      Under    9.5       -9900
1948        TJ McConnell  IND    204456      Under    9.5       -9900
1949        LeBron James  LAL      2544      Under    9.5       -9900

[3705 rows x 6 columns]

In [5]:
run.run_model('threes','2026-03-23',)

NameError: name 'run' is not defined

In [403]:
pd.read_sql('select * from predictions',etl.conn)

     player_id        date  market over_under  number  model_line
0      1626166  2026-03-23  threes       Over     0.5      -461.0
1      1626167  2026-03-23  threes       Over     0.5      -306.0
2      1626171  2026-03-23  threes       Over     0.5      -355.0
3      1626181  2026-03-23  threes       Over     0.5     -2657.0
4      1627739  2026-03-23  threes       Over     0.5      -123.0
...        ...         ...     ...        ...     ...         ...
3700    203991  2026-03-23  threes      Under     9.5     -9900.0
3701    203992  2026-03-23  threes      Under     9.5     -9900.0
3702    204001  2026-03-23  threes      Under     9.5     -9900.0
3703    204456  2026-03-23  threes      Under     9.5     -9900.0
3704      2544  2026-03-23  threes      Under     9.5     -9900.0

[3705 rows x 6 columns]

In [397]:
pd.read_sql('''select Case when 
from teamLog left join teams using (team_id) 
where game_date = '2026-03-23' 
group by game_id

            
            ''',etl.conn)

,game_id,game_date,team_id,opp_id,attendance,home,inactive,count_inactive,assist_percentage,offensive_rating,...,ot4_pts,win,season,teamAbrv,teamName,teamConference,teamDivision,teamLong,teamLAT,stad_capacity
0,0022501043,2026-03-23,1610612762,1610612761,18186,1,"1641718,1642396,1628991,1631117,1628374,203994",6,0.641,115.5,...,None,0,2025-26,UTA,Utah Jazz,West,Northwest,None,None,18306
1,0022501043,2026-03-23,1610612761,1610612762,0,0,"1642935,1630639,1642918,1627751,1630193",5,0.907,131.2,...,None,1,2025-26,TOR,Toronto Raptors,East,Atlantic,None,None,19800
2,0022501037,2026-03-23,1610612737,1610612763,16131,1,"1642484,1642933,1630552,1642854",4,0.755,140.4,...,None,1,2025-26,ATL,Atlanta Hawks,East,Southeast,None,None,17044
3,0022501037,2026-03-23,1610612763,1610612737,0,0,"1630583,203484,1642907,1641744,1642942,1629630...",8,0.571,103.9,...,None,0,2025-26,MEM,Memphis Grizzles,West,Southwest,None,None,17794
4,0022501038,2026-03-23,1610612765,1610612747,20180,1,"1630595,1642403,1641752,1631111,1631204,1630191",6,0.775,120.2,...,None,1,2025-26,DET,Detroit Pistons,East,Central,None,None,20332
5,0022501038,2026-03-23,1610612747,1610612765,0,0,"1629060,1643024,203935,1641733",4,0.711,115.8,...,None,0,2025-26,LAL,Los Angelels Lakers,West,Pacific,None,None,18997
6,0022501044,2026-03-23,1610612742,1610612744,18821,1,"1630619,202681,1641726,1628997,1630314",5,0.725,115.9,...,None,0,2025-26,DAL,Dallas Mavericks,West,Southwest,None,None,19200
7,0022501044,2026-03-23,1610612744,1610612742,0,0,"202710,203552,201939,201143,1631466",5,0.765,119.1,...,None,1,2025-26,GSW,Golden State Warriors,West,Pacific,None,None,18064
8,0022501039,2026-03-23,1610612753,1610612754,17721,1,"1641710,1628371,1630591,1630532",4,0.604,128.6,...,None,0,2025-26,ORL,Orlando Magic,East,Southeast,None,None,18846
9,0022501039,2026-03-23,1610612754,1610612753,0,0,"1642277,1630169,1643007,1641771,1630679,1627826",6,0.711,132.0,...,None,1,2025-26,IND,Indiana Pacers,East,Central,None,None,17923
10,0022501040,2026-03-23,1610612755,1610612760,19746,1,"1641780,203954,202331,1629656,1630178,1626162",6,0.707,103.0,...,None,0,2025-26,PHI,Philadelphia 76ers,East,Atlantic,None,None,20007
11,0022501040,2026-03-23,1610612760,1610612755,0,0,"1642362,1642850,1642260",3,0.688,121.8,...,None,1,2025-26,OKC,Oklahoma City,West,Northwest,None,None,18203
12,0022501045,2026-03-23,1610612757,1610612751,17059,1,"1643257,203081,1631126",3,0.636,125.2,...,None,1,2025-26,POR,Portland Trailblazers,West,Northwest,None,None,19411
13,0022501045,2026-03-23,1610612751,1610612757,0,0,"1641730,1642856,1629611,1629008,1642962,1630549",6,0.667,91.7,...,None,0,2025-26,BKN,Brooklyn Nets,East,Atlantic,None,None,17732
14,0022501046,2026-03-23,1610612746,1610612749,16515,1,"203078,1628381,1631097,1642949,1641807",5,0.638,133.0,...,None,1,2025-26,LAC,Los Angelels Clippers,West,Pacific,None,None,18000
15,0022501046,2026-03-23,1610612749,1610612746,0,0,"1630828,203507,203914,1628398,1629645,1642504,...",7,0.784,99.0,...,None,0,2025-26,MIL,Oklahoma City Thunder,East,Central,None,None,17341
16,0022501042,2026-03-23,1610612741,1610612745,21395,1,"1628380,1642855,1631093,1642530,1630644,1629014",6,0.667,121.1,...,None,1,2025-26,CHI,Chicago Bulls,East,Central,None,None,20917
17,0022501042,2026-03-23,1610612745,1610612741,0,0,"203500,1631120,1641803,1627832",4,0.551,113.8,...,None,0,2025-26,HOU,Houston Rockers,West,Southwest,None,None,18055
18,0022501041,2026-03-23,1610612748,1610612759,19784,1,"1642884,1631211,1626179,1642443",4,0.763,103.7,...,None,0,2025-26,MIA,Miami Heat,East,Southeast,None,None,19600
19,0022501041,2026-03-23,1610612759,1610612748,0,0,"1631127,1642357,1641801",3,0.688,127.1,...,None,1,2025-26,SAS,San Antonio Spus,West,Southwest,None,None,18354